name: PR Checklist

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Checklist
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload.pull_request.body);
            const checklist = context.payload.pull_request.body.match(/- \[x\]|\* \[x\]/g) || [];
            const isChecklistComplete = checklist.length === 3;
            context.payload.pull_request.state = isChecklistComplete ? 'success' : 'failure'
            console.log(`PR Checklist Complete: ${isChecklistComplete}`);

            # github.repos.createStatus({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   sha: context.payload.pull_request.head.sha,
            #   state: isChecklistComplete ? 'success' : 'failure',
            #   context: 'pr-checklist',
            #   description: isChecklistComplete
            #     ? 'PR Checklist is complete'
            #     : 'PR Checklist is incomplete',
            # });
